Add Shaka player
GeneticGenesis/phils-players pull request #13
Opened 2017-05-10 12:17 UTC by sparrc

2017-07-06 14:52 UTC, stuarthicks requested changes

2017-07-06 14:52 UTC, stuarthicks commented on js/shaka.js
> +document.addEventListener('DOMContentLoaded', initApp);
Missing newline at end of file

2017-07-06 14:58 UTC, sparrc commented on js/shaka.js
> +document.addEventListener('DOMContentLoaded', initApp);
done

2017-07-10 13:48 UTC, stuarthicks approved these changes

2017-07-10 13:48 UTC, merged